# Generated by Django 3.2.12 on 2023-06-06 08:10

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('specialist_in', models.CharField(blank=True, choices=[('cardiology', 'cardiology'), ('dermatology', 'dermatology'), ('pediatrics', 'pediatrics'), ('neurology', 'neurology'), ('gastroenterology', 'gastroenterology'), ('eye-centre', 'eye-centre'), ('ear-nose-throat', 'ear-nose-throat'), ('urology', 'urology'), ('oncology', 'oncology')], max_length=50, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('role', models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cardiology', 'cardiology'), ('dermatology', 'dermatology'), ('pediatrics', 'pediatrics'), ('neurology', 'neurology'), ('gastroenterology', 'gastroenterology'), ('eye-centre', 'eye-centre'), ('ear-nose-throat', 'ear-nose-throat'), ('urology', 'urology'), ('oncology', 'oncology')], max_length=50)),
                ('appointment_date', models.DateField(default=app.models.current_date)),
                ('time_slot', models.TimeField(default=datetime.time(9, 0))),
                ('doctor', models.ForeignKey(default=5, limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='app.userwithusertype')),
                ('patient', models.ForeignKey(default=7, limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='app.userwithusertype')),
            ],
        ),
    ]
