# Generated by Django 3.2.12 on 2023-06-12 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
