# Generated by Django 3.2.12 on 2023-06-14 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
