# Generated by Django 3.2.12 on 2023-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithusertype',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
