# Generated by Django 3.2.12 on 2023-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userwithusertype_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithusertype',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
